/**
 * What the icon set must be true of, whatever the mark looks like.
 *
 * The art is a design decision and is not tested here. These are the three
 * things about the FILES that break a shipped product rather than an opinion:
 * an App Store upload refused, a mark that is too faint to see when small, and
 * a set whose sizes disagree because they were exported one at a time.
 *
 * Everything under `assets/` is generated by `scripts/derive-icons.py` from the
 * four masters. If one of these fails, re-run it rather than editing a PNG.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const at = (p) => path.join(root, p);

/** Width, height and colour type, straight out of the PNG header. */
function pngHead(file) {
  const b = fs.readFileSync(file);
  assert.equal(b.subarray(1, 4).toString('ascii'), 'PNG', `${file} is not a PNG`);
  return {
    width: b.readUInt32BE(16),
    height: b.readUInt32BE(20),
    // 0 grey, 2 RGB, 3 palette, 4 grey+alpha, 6 RGBA
    colourType: b[25],
  };
}

test('the iPhone icon carries no alpha channel', () => {
  // App Store Connect refuses an app icon with one, and the refusal arrives
  // at upload time — after the build, the archive and the wait.
  const icon = at('ios/KhaytCompanion/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png');
  const head = pngHead(icon);
  assert.equal(head.width, 1024);
  assert.equal(head.height, 1024);
  assert.ok(head.colourType === 0 || head.colourType === 2 || head.colourType === 3,
            `AppIcon.png has an alpha channel (colour type ${head.colourType})`);
});

test('apple-touch-icon is opaque too, because iOS composites alpha onto black', () => {
  const head = pngHead(at('assets/logo/apple-touch-icon.png'));
  assert.equal(head.width, 180);
  assert.ok(head.colourType !== 6 && head.colourType !== 4,
            'apple-touch-icon.png has an alpha channel');
});

test('every size in the iconset is the size its name claims', () => {
  const dir = at('assets/khayt.iconset');
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.png'));
  assert.ok(files.length >= 13, `only ${files.length} icons in the iconset`);
  for (const f of files) {
    const m = f.match(/^icon_(\d+)x\1(@2x)?\.png$/);
    assert.ok(m, `${f} is not a name iconutil understands`);
    const want = Number(m[1]) * (m[2] ? 2 : 1);
    const head = pngHead(path.join(dir, f));
    assert.equal(head.width, want, `${f} is ${head.width}px`);
    assert.equal(head.height, want, `${f} is ${head.height}px tall`);
  }
});

test('the masters the whole set is derived from are all present', () => {
  // A missing master is not an error at generation time — `derive-icons.py`
  // falls back to the full mark when `fg-small.png` is absent, which silently
  // ships the detailed art at 16px, where it is a smudge.
  for (const [name, px] of [['fg.png', 2048], ['fg-small.png', 1024],
                            ['mono.png', 1024]]) {
    const head = pngHead(at(path.join('assets/icon-masters', name)));
    assert.equal(head.width, px, `${name} is ${head.width}px, not ${px}`);
    assert.equal(head.colourType, 6, `${name} must be RGBA — the ground is added later`);
  }
});
