'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { extract, extractGcodeThumbnail, extract3mf, normHex } = require('../lib/thumbnail-extract');
const { makeZip } = require('./helpers/make-zip');

test('gcode: picks the largest embedded PNG thumbnail', () => {
  const gcode = [
    '; generated by PrusaSlicer',
    '; thumbnail begin 16x16 8',
    '; aGVsbG8=',
    '; thumbnail end',
    'G1 X0 Y0',
    '; thumbnail begin 32x32 8',
    '; d29ybGQ=',
    '; thumbnail end',
  ].join('\n');
  const t = extractGcodeThumbnail(gcode);
  assert.equal(t.width, 32);
  assert.equal(t.pngBase64, 'd29ybGQ='); // "world" — the bigger block wins
});

test('gcode: no thumbnail → null', () => {
  assert.equal(extractGcodeThumbnail('G1 X0\nG1 Y0\n').pngBase64, null);
  assert.equal(extractGcodeThumbnail('').pngBase64, null);
});

test('gcode: QOI blocks are ignored (not PNG "thumbnail begin")', () => {
  const g = '; thumbnail_QOI begin 48x48 4\n; AAAA\n; thumbnail_QOI end\n';
  assert.equal(extractGcodeThumbnail(g).pngBase64, null);
});

test('3mf: extracts embedded PNG + colours + swap estimate', () => {
  const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3, 4]);
  const sliceInfo = `<?xml version="1.0"?>
<config><plate>
  <filament id="1" tray_info_idx="GFA00" type="PLA" color="#ff0000" used_g="12.5" used_m="4.2"/>
  <filament id="2" type="PLA" color="#00FF00" used_g="3.1" used_m="1.0"/>
</plate></config>`;
  const zip = makeZip([
    { name: 'Metadata/thumbnail.png', data: png, method: 0 },
    { name: 'Metadata/slice_info.config', data: sliceInfo, method: 8 },
    { name: '3D/3dmodel.model', data: '<model/>', method: 8 },
  ]);
  const r = extract3mf(zip);
  assert.equal(r.pngBase64, png.toString('base64'));
  assert.equal(r.colors.length, 2);
  assert.equal(r.colors[0].hex, '#FF0000');
  assert.equal(r.colors[0].grams, 12.5);
  assert.equal(r.colors[1].hex, '#00FF00');
  assert.equal(r.swapCount, 1); // 2 colours, single-extruder floor
});

test('3mf: falls back to project_settings filament_colour when no slice_info', () => {
  const proj = '{"filament_colour":["#112233","#445566","#112233"],"other":1}';
  const zip = makeZip([{ name: 'Metadata/project_settings.config', data: proj, method: 8 }]);
  const r = extract3mf(zip);
  assert.deepEqual(r.colors.map((c) => c.hex), ['#112233', '#445566']); // deduped
  assert.equal(r.pngBase64, null);
});

test('3mf: garbage buffer → empty result, no throw', () => {
  const r = extract3mf(Buffer.from('nonsense'));
  assert.equal(r.pngBase64, null);
  assert.deepEqual(r.colors, []);
});

test('extract() dispatches by extension', () => {
  const g = '; thumbnail begin 8x8 4\n; QUJDRA==\n; thumbnail end\n';
  const eg = extract({ ext: 'gcode', text: g });
  assert.equal(eg.pngBase64, 'QUJDRA==');
  assert.equal(eg.source, 'embedded');
  const eNone = extract({ ext: 'stl', buf: Buffer.from('x') });
  assert.equal(eNone.source, null);
});

test('normHex normalises shorthand + strips alpha', () => {
  assert.equal(normHex('#abc'), '#AABBCC');
  assert.equal(normHex('ff8800'), '#FF8800');
  assert.equal(normHex('#11223344'), '#112233');
  assert.equal(normHex('nope'), null);
});

/**
 * THE LIFT PROOF for `colorsFromConfigs`.
 *
 * `parse3mfColors` used to hold both the rule and the reading of four zip
 * members. The rule is now `colorsFromConfigs`, taking the config TEXT, so a
 * host that opens a 3MF some other way can still use it — the Mac app has to,
 * because `lib/zip-read.js` needs Buffer and zlib and JavaScriptCore has
 * neither.
 *
 * A split like that is only safe if it changed nothing, so the ORIGINAL
 * function is copied in verbatim below and both are run over the same inputs.
 * The generated cases cover all three slicer shapes and their awkward edges;
 * the real ones are whatever 3MF files are on the machine.
 */
const { colorsFromConfigs, parse3mfColors, normHex: normHexForProof } = require('../lib/thumbnail-extract');

/** `parse3mfColors` exactly as it stood before the split. */
function ORIGINAL_parse3mfColors(zip) {
  const colors = [];
  const seen = new Set();
  const push = (hex, grams, label) => {
    const h = normHexForProof(hex);
    if (!h) return;
    if (seen.has(h)) {
      // One deliberate change since the split (Oct 2026): a colour met again —
      // the same spool on a later plate — ADDS its grams instead of keeping
      // the first plate's. See the multi-plate test below.
      if (grams != null) {
        const e = colors.find((c) => c.hex === h);
        if (e) e.grams = e.grams == null ? grams : Math.round((e.grams + grams) * 100) / 100;
      }
      return;
    }
    seen.add(h);
    colors.push({ hex: h, grams: (grams != null ? grams : null), label: label || ('Filament ' + (colors.length + 1)) });
  };
  const cfgText = (name) => { const b = zip.file(name); return b ? b.toString('utf8') : ''; };
  const slice = cfgText('Metadata/slice_info.config');
  let usedFilaments = 0;
  if (slice) {
    const fre = /<filament\b[^>]*>/g; let fm;
    while ((fm = fre.exec(slice)) !== null) {
      const tag = fm[0];
      const color = /\bcolou?r\s*=\s*"([^"]+)"/i.exec(tag);
      const usedG = /\bused_g\s*=\s*"([\d.]+)"/i.exec(tag);
      const tray = /\btray_info_idx\b/i.test(tag);
      if (color) { push(color[1], usedG ? parseFloat(usedG[1]) : null, tray ? null : null); usedFilaments++; }
    }
  }
  if (!colors.length) {
    const proj = cfgText('Metadata/project_settings.config') || cfgText('Metadata/model_settings.config');
    const arr = /"filament_colou?r"\s*:\s*\[([^\]]*)\]/i.exec(proj);
    if (arr) (arr[1].match(/#?[0-9a-fA-F]{6,8}/g) || []).forEach((h) => push(h));
  }
  if (!colors.length) {
    const prusa = cfgText('Metadata/Slic3r_PE.config') || cfgText('Metadata/Prusa_Slicer.config');
    const line = /filament_colou?r\s*=\s*([#0-9a-fA-F;,\s]+)/i.exec(prusa);
    if (line) (line[1].match(/#?[0-9a-fA-F]{6,8}/g) || []).forEach((h) => push(h));
  }
  let swapCount = 0;
  const chg = /(?:filament[_\s]*changes?|total[_\s]*filament[_\s]*change)\D*(\d+)/i.exec(slice || '');
  if (chg) swapCount = parseInt(chg[1], 10);
  else if (colors.length > 1) swapCount = colors.length - 1;
  return { colors, swapCount, usedFilaments };
}

/** A zip-like object over `{name: text}`, so a case needs no archive. */
const fakeZip = (files) => ({ file: (n) => (files[n] != null ? Buffer.from(files[n], 'utf8') : null) });

test('colorsFromConfigs: the split changed nothing, across every slicer shape', () => {
  const cases = [];
  const hexes = ['#FF0000', '00FF00', '#0000FFAA', 'nonsense', '', '#abc', '#AABBCC'];
  for (const h of hexes) {
    for (const g of ['12.5', '', 'x']) {
      cases.push({ 'Metadata/slice_info.config': `<filament id="1" color="${h}" used_g="${g}"/>` });
      cases.push({ 'Metadata/slice_info.config': `<filament id="1" colour="${h}" tray_info_idx="3"/>` });
      cases.push({ 'Metadata/project_settings.config': `{"filament_colour": ["${h}","#123456"]}` });
      cases.push({ 'Metadata/model_settings.config': `{"filament_color": ["${h}"]}` });
      cases.push({ 'Metadata/Slic3r_PE.config': `filament_colour = ${h};#654321` });
      cases.push({ 'Metadata/Prusa_Slicer.config': `filament_color = ${h}` });
    }
  }
  cases.push({});
  cases.push({ 'Metadata/slice_info.config': '<filament color="#FF0000"/><filament color="#FF0000" used_g="4"/>' });
  cases.push({ 'Metadata/slice_info.config': 'total_filament_changes 7 <filament color="#FF0000"/>' });
  cases.push({ 'Metadata/slice_info.config': '<filament color="#111111"/><filament color="#222222"/><filament color="#333333"/>' });
  // Both present. The order between these two is the rule's, not alphabetical,
  // and moving the names into the adapter is exactly where that could be lost.
  cases.push({ 'Metadata/project_settings.config': '{"filament_colour": ["#AAAAAA"]}',
               'Metadata/model_settings.config': '{"filament_colour": ["#BBBBBB"]}' });
  cases.push({ 'Metadata/Slic3r_PE.config': 'filament_colour = #CCCCCC',
               'Metadata/Prusa_Slicer.config': 'filament_colour = #DDDDDD' });

  for (const files of cases) {
    assert.deepEqual(parse3mfColors(fakeZip(files)), ORIGINAL_parse3mfColors(fakeZip(files)),
      `differs for ${JSON.stringify(files)}`);
  }
  assert.ok(cases.length > 120, 'the corpus shrank');
});

test('colorsFromConfigs: the rule reads the same text the adapter would hand it', () => {
  const files = {
    'Metadata/slice_info.config': '<filament id="1" color="#6B7A3B" used_g="120.5"/>'
                                + '<filament id="2" color="#C2A24E"/>',
  };
  assert.deepEqual(
    colorsFromConfigs({ sliceInfo: files['Metadata/slice_info.config'] }),
    parse3mfColors(fakeZip(files)),
    'the adapter and the rule must agree when given the same bytes');
});

test('colorsFromConfigs: nothing in, nothing invented', () => {
  for (const input of [undefined, null, {}, { sliceInfo: '' }, { projectSettings: '{}' }]) {
    const out = colorsFromConfigs(input);
    assert.deepEqual(out.colors, []);
    assert.equal(out.swapCount, 0);
  }
});

/** Whatever 3MF files are on this machine. Skipped where there are none. */
test('colorsFromConfigs: the split changed nothing on real 3MF files', () => {
  const fs = require('node:fs');
  const path = require('node:path');
  const Z = require('../lib/zip-read.js');
  const dir = path.join(process.env.HOME || '', 'kingfix');
  if (!fs.existsSync(dir)) return;
  const files = fs.readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.3mf')).slice(0, 6);
  for (const name of files) {
    const zip = Z.openZip(fs.readFileSync(path.join(dir, name)));
    assert.deepEqual(parse3mfColors(zip), ORIGINAL_parse3mfColors(zip), `differs on ${name}`);
  }
});
