import Foundation
import CommonCrypto

/// A staff PIN, hashed and checked — `lib/pin-hash.js`, ported to Swift.
///
/// The JavaScript needs `node:crypto` (PBKDF2, a CSPRNG, a constant-time
/// compare), which JavaScriptCore does not have, so this is a port rather than
/// a binding. That makes it the kind of code that drifts: `PinHashTests` runs
/// it over vectors generated BY the JavaScript module (the fixture records
/// which), and every one must agree, including the malformed ones.
///
/// Two formats, both read:
///
///     p2$<iterations>$<saltHex>$<derivedHex>   PBKDF2-SHA256, the one written
///     <64 hex>                                 unsalted SHA-256, legacy
///
/// Anything else verifies as false. Never logs, prints or returns a PIN or a
/// hash it did not write.
public enum PinHash {

    public static let prefix = "p2"
    /// What a new hash is written with: the module's `PBKDF2_ITERS`.
    public static let iterations = 200_000
    public static let keyLength = 32

    /// The most iterations a STORED hash may ask for before it is refused.
    ///
    /// Not in the JavaScript, and on purpose here: the iteration count is read
    /// out of the book, and the book travels — backups, cloud sync, a file a
    /// stranger hands a shop. "p2$4000000000$…" would make one PIN check hold
    /// this Mac's CPU for hours. Fifty times what is written is room for any
    /// future raise and nothing near that.
    public static let maxIterations = 10_000_000

    public static func isPbkdf2(_ stored: String) -> Bool {
        let parts = stored.split(separator: "$", omittingEmptySubsequences: false)
        guard parts.count == 4, parts[0] == Substring(prefix),
              !parts[1].isEmpty, parts[1].allSatisfy({ $0.isASCII && $0.isNumber }),
              !parts[2].isEmpty, parts[2].allSatisfy(\.isHexDigit),
              !parts[3].isEmpty, parts[3].allSatisfy(\.isHexDigit) else { return false }
        return true
    }

    public static func isLegacySha256(_ stored: String) -> Bool {
        stored.count == 64 && stored.allSatisfy { $0.isASCII && $0.isHexDigit }
    }

    /// A format this can verify.
    public static func isManaged(_ stored: String) -> Bool { isPbkdf2(stored) || isLegacySha256(stored) }

    /// Should a correct PIN re-hash this one into the salted format?
    public static func needsUpgrade(_ stored: String) -> Bool { isLegacySha256(stored) }

    /// A PIN as its digits, whichever keyboard typed them — Arabic-Indic
    /// (٠-٩) and Persian (۰-۹) to 0-9. `lib/pin-hash.js` `normalizePin`,
    /// exactly: the Arabic layout types the first, and the same PIN typed two
    /// ways was refused when set and counted wrong at sign-in.
    public static func normalize(_ plain: String) -> String {
        String(String.UnicodeScalarView(plain.unicodeScalars.map { s -> Unicode.Scalar in
            switch s.value {
            case 0x0660...0x0669: return Unicode.Scalar(s.value - 0x0660 + 0x30)!
            case 0x06F0...0x06F9: return Unicode.Scalar(s.value - 0x06F0 + 0x30)!
            default: return s
            }
        }))
    }

    /// A new salted hash, in the format above, of the PIN's digits.
    public static func hash(_ plain: String, iterations: Int = iterations) -> String? {
        var salt = [UInt8](repeating: 0, count: 16)
        guard SecRandomCopyBytes(kSecRandomDefault, salt.count, &salt) == errSecSuccess,
              let dk = pbkdf2(normalize(plain), salt: salt, iterations: iterations, length: keyLength) else { return nil }
        return "\(prefix)$\(iterations)$\(hex(salt))$\(hex(dk))"
    }

    /// Does `plain` match `stored`? The digits first, then — when they
    /// differ — the text as typed, so a PIN hashed from Arabic digits before
    /// `normalize` still opens (the JavaScript's order). Constant time in each
    /// compare.
    public static func verify(_ plain: String, _ stored: String) -> Bool {
        let digits = normalize(plain)
        if verifyExact(digits, stored) { return true }
        return digits != plain && verifyExact(plain, stored)
    }

    static func verifyExact(_ plain: String, _ stored: String) -> Bool {
        if isPbkdf2(stored) {
            let parts = stored.split(separator: "$", omittingEmptySubsequences: false)
            // `parseInt` in the JavaScript: "0" and anything unparseable fail.
            guard let iters = Int(parts[1]), iters > 0, iters <= maxIterations,
                  let salt = bytes(String(parts[2])), let expected = bytes(String(parts[3])),
                  !expected.isEmpty,
                  let dk = pbkdf2(plain, salt: salt, iterations: iters, length: expected.count)
            else { return false }
            return constantTimeEqual(dk, expected)
        }
        if isLegacySha256(stored) {
            guard let expected = bytes(stored) else { return false }
            return constantTimeEqual(sha256(Array(plain.utf8)), expected)
        }
        return false
    }

    // MARK: - The pieces

    static func pbkdf2(_ plain: String, salt: [UInt8], iterations: Int, length: Int) -> [UInt8]? {
        guard iterations > 0, length > 0 else { return nil }
        let password = Array(plain.utf8)
        var out = [UInt8](repeating: 0, count: length)
        let status = password.withUnsafeBufferPointer { pw in
            CCKeyDerivationPBKDF(CCPBKDFAlgorithm(kCCPBKDF2),
                                 pw.baseAddress.map { UnsafeRawPointer($0).assumingMemoryBound(to: CChar.self) },
                                 password.count,
                                 salt, salt.count,
                                 CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA256),
                                 UInt32(clamping: iterations),
                                 &out, length)
        }
        return status == kCCSuccess ? out : nil
    }

    static func sha256(_ data: [UInt8]) -> [UInt8] {
        var digest = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
        _ = data.withUnsafeBufferPointer { CC_SHA256($0.baseAddress, CC_LONG($0.count), &digest) }
        return digest
    }

    /// Hex to bytes. Node's `Buffer.from(x, 'hex')` stops at the first bad pair
    /// and drops an odd last digit; the format check above has already
    /// refused non-hex, so only the odd length is left to match.
    static func bytes(_ hex: String) -> [UInt8]? {
        let chars = Array(hex.utf8)
        var out: [UInt8] = []
        out.reserveCapacity(chars.count / 2)
        var i = 0
        while i + 1 < chars.count {
            guard let hi = nibble(chars[i]), let lo = nibble(chars[i + 1]) else { return nil }
            out.append(hi << 4 | lo)
            i += 2
        }
        return out
    }

    private static func nibble(_ c: UInt8) -> UInt8? {
        switch c {
        case 48...57: c - 48
        case 97...102: c - 87
        case 65...70: c - 55
        default: nil
        }
    }

    static func hex(_ bytes: [UInt8]) -> String {
        bytes.map { String(format: "%02x", $0) }.joined()
    }

    /// Every byte looked at whatever the answer; unequal lengths are unequal.
    static func constantTimeEqual(_ a: [UInt8], _ b: [UInt8]) -> Bool {
        guard a.count == b.count else { return false }
        var diff: UInt8 = 0
        for i in a.indices { diff |= a[i] ^ b[i] }
        return diff == 0
    }
}
