import Foundation
import Testing
@testable import KhaytApp
import KhaytCore

/// "I just tried it but it didn't get the info from the file" (Sep 2026).
struct SlicerFiguresTests {
    static let sliceInfo = """
    <?xml version='1.0' encoding='utf-8'?>
    <config><plate>
      <metadata key="printer_model_id" value="Snapmaker U1" />
      <metadata key="prediction" value="16629" />
      <metadata key="weight" value="57.17" />
      <filament id="1" type="PLA" color="#ffff00" used_m="9.55" used_g="28.93" />
      <filament id="2" type="PLA" color="#000000" used_m="0.61" used_g="1.85" />
      <filament id="3" type="PLA" color="#ffffff" used_m="5.08" used_g="15.41" />
      <filament id="4" type="PLA" color="#ff8040" used_m="3.63" used_g="10.99" />
    </plate></config>
    """

    func zip(_ members: [String: String]) throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        for (name, text) in members {
            let url = dir.appending(path: name)
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try Data(text.utf8).write(to: url)
        }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        p.arguments = ["-q", "-r", "model.3mf"] + Array(members.keys)
        p.currentDirectoryURL = dir
        try p.run(); p.waitUntilExit()
        return dir.appending(path: "model.3mf")
    }

    @Test("a Snapmaker/Bambu/Orca 3MF: the slicer's time, weight and material, not a guess")
    func sliceInfo3mf() async throws {
        let url = try zip(["Metadata/slice_info.config": Self.sliceInfo, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(277), "16629 s is 4 h 37 min")
        guard case .number(let g)? = parsed["filamentGrams"] else { Issue.record("no grams"); return }
        #expect(abs(g - 57.18) < 0.05, "the shared rule rounds to 0.1 g")
        #expect(parsed["filamentType"] == .string("PLA"))
    }

    @Test("a G-code: the slicer's own summary")
    func gcode() async throws {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appending(path: "part.gcode")
        let body = String(repeating: "G1 X1 Y1\n", count: 20_000)
        try Data(("; generated by PrusaSlicer 2.8\n" + body
                  + "; filament used [g] = 42.5\n; estimated printing time (normal mode) = 2h 5m 0s\n; filament_type = PETG\n").utf8)
            .write(to: url)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["filamentGrams"] == .number(42.5))
        #expect(parsed["printTimeMins"] == .number(125))
    }

    @Test("an unsliced model says nothing rather than guessing")
    func unsliced() async throws {
        let url = try zip(["3D/3dmodel.model": "<model/>"])
        #expect(await SlicerFigures.read(url, engine: try KhaytEngine()) == nil)
    }

    /// Opt-in, against a real file on this Mac: `KHAYT_REAL_3MF=/path swift test`.
    @Test("the shop's own file", .enabled(if: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"] != nil))
    func realFile() async throws {
        let url = URL(fileURLWithPath: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"]!)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        print("REAL:", parsed)
    }
}
