import Foundation
import Testing
@testable import KhaytApp
import KhaytCore

/// "I just tried it but it didn't get the info from the file" (Sep 2026).
struct SlicerFiguresTests {
    static let sliceInfo = """
    <?xml version='1.0' encoding='utf-8'?>
    <config><plate>
      <metadata key="printer_model_id" value="Snapmaker U1" />
      <metadata key="prediction" value="16629" />
      <metadata key="weight" value="57.17" />
      <filament id="1" type="PLA" color="#ffff00" used_m="9.55" used_g="28.93" />
      <filament id="2" type="PLA" color="#000000" used_m="0.61" used_g="1.85" />
      <filament id="3" type="PLA" color="#ffffff" used_m="5.08" used_g="15.41" />
      <filament id="4" type="PLA" color="#ff8040" used_m="3.63" used_g="10.99" />
    </plate></config>
    """

    func zip(_ members: [String: String]) throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        for (name, text) in members {
            let url = dir.appending(path: name)
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try Data(text.utf8).write(to: url)
        }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        p.arguments = ["-q", "-r", "model.3mf"] + Array(members.keys)
        p.currentDirectoryURL = dir
        try p.run(); p.waitUntilExit()
        return dir.appending(path: "model.3mf")
    }

    @Test("a Snapmaker/Bambu/Orca 3MF: the slicer's time, weight and material, not a guess")
    func sliceInfo3mf() async throws {
        let url = try zip(["Metadata/slice_info.config": Self.sliceInfo, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(277), "16629 s is 4 h 37 min")
        guard case .number(let g)? = parsed["filamentGrams"] else { Issue.record("no grams"); return }
        #expect(abs(g - 57.18) < 0.05, "the shared rule rounds to 0.1 g")
        #expect(parsed["filamentType"] == .string("PLA"))
    }

    @Test("a G-code: the slicer's own summary")
    func gcode() async throws {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appending(path: "part.gcode")
        let body = String(repeating: "G1 X1 Y1\n", count: 20_000)
        try Data(("; generated by PrusaSlicer 2.8\n" + body
                  + "; filament used [g] = 42.5\n; estimated printing time (normal mode) = 2h 5m 0s\n; filament_type = PETG\n").utf8)
            .write(to: url)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["filamentGrams"] == .number(42.5))
        #expect(parsed["printTimeMins"] == .number(125))
    }

    @Test("an unsliced model says nothing rather than guessing")
    func unsliced() async throws {
        let url = try zip(["3D/3dmodel.model": "<model/>"])
        #expect(await SlicerFigures.read(url, engine: try KhaytEngine()) == nil)
    }

    /// Opt-in, against a real file on this Mac: `KHAYT_REAL_3MF=/path swift test`.
    @Test("the shop's own file", .enabled(if: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"] != nil))
    func realFile() async throws {
        let url = URL(fileURLWithPath: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"]!)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        print("REAL:", parsed)
    }

    @Test("two plates: the file is their SUM, and each plate is kept to be chosen")
    func twoPlates() async throws {
        let info = """
        <config>
        <plate><metadata key="index" value="1" /><metadata key="prediction" value="39284" />
          <filament id="1" type="PETG" used_g="143.44" /></plate>
        <plate><metadata key="index" value="2" /><metadata key="prediction" value="39154" />
          <filament id="1" type="PETG" used_g="100.00" /><filament id="2" type="PETG" used_g="42.95" /></plate>
        </config>
        """
        let url = try zip(["Metadata/slice_info.config": info, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(655 + 653), "BOTH plates' time, not the first plate's")
        #expect(parsed["filamentGrams"] == .number(286.39))
        #expect(parsed["platesRead"] == .bool(true))
        guard case .array(let plates)? = parsed["plates"], plates.count == 2,
              case .object(let p2) = plates[1] else { Issue.record("no plates"); return }
        #expect(p2["index"] == .number(2) && p2["printTimeMins"] == .number(653) && p2["filamentGrams"] == .number(142.95))
    }

    @Test("a record is read again when it has no figures, or is a 3MF read before plates were")
    func due() {
        #expect(Shop.slicerFiguresDue(nil, ext: "3mf"))
        #expect(Shop.slicerFiguresDue(.object([:]), ext: "gcode"))
        #expect(Shop.slicerFiguresDue(.object(["printTimeMins": .number(5)]), ext: "3mf"))
        #expect(!Shop.slicerFiguresDue(.object(["printTimeMins": .number(5)]), ext: "gcode"))
        #expect(!Shop.slicerFiguresDue(.object(["printTimeMins": .number(5), "platesRead": .bool(true)]), ext: "3mf"))
    }

    @Test("a Bambu print file carrying plate 1's G-code is still read plate by plate")
    func printFileWithGcode() async throws {
        let info = """
        <config>
        <plate><metadata key="index" value="1" /><metadata key="prediction" value="3600" />
          <filament id="1" type="PLA" used_g="10" /></plate>
        <plate><metadata key="index" value="2" /><metadata key="prediction" value="7200" />
          <filament id="1" type="PLA" used_g="20" /></plate>
        </config>
        """
        let gcode = "; generated by BambuStudio\n; filament used [g] = 10\n; estimated printing time (normal mode) = 1h 0m 0s\n"
        let url = try zip(["Metadata/slice_info.config": info, "Metadata/plate_1.gcode": gcode, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(180), "both plates, not plate 1's G-code")
        #expect(parsed["filamentGrams"] == .number(30))
    }

    @Test("an unsliced 3MF says nothing — and is marked read, so it is not opened every launch")
    func unslicedMarked() {
        #expect(!Shop.slicerFiguresDue(.object(["platesRead": .bool(true)]), ext: "3mf"))
    }
}
