import Foundation
import Testing
@testable import KhaytApp
import KhaytCore

/// "I just tried it but it didn't get the info from the file" (Sep 2026).
struct SlicerFiguresTests {
    static let sliceInfo = """
    <?xml version='1.0' encoding='utf-8'?>
    <config><plate>
      <metadata key="printer_model_id" value="Snapmaker U1" />
      <metadata key="prediction" value="16629" />
      <metadata key="weight" value="57.17" />
      <filament id="1" type="PLA" color="#ffff00" used_m="9.55" used_g="28.93" />
      <filament id="2" type="PLA" color="#000000" used_m="0.61" used_g="1.85" />
      <filament id="3" type="PLA" color="#ffffff" used_m="5.08" used_g="15.41" />
      <filament id="4" type="PLA" color="#ff8040" used_m="3.63" used_g="10.99" />
    </plate></config>
    """

    func zip(_ members: [String: String]) throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        for (name, text) in members {
            let url = dir.appending(path: name)
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try Data(text.utf8).write(to: url)
        }
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        p.arguments = ["-q", "-r", "model.3mf"] + Array(members.keys)
        p.currentDirectoryURL = dir
        try p.run(); p.waitUntilExit()
        return dir.appending(path: "model.3mf")
    }

    @Test("a Snapmaker/Bambu/Orca 3MF: the slicer's time, weight and material, not a guess")
    func sliceInfo3mf() async throws {
        let url = try zip(["Metadata/slice_info.config": Self.sliceInfo, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(277), "16629 s is 4 h 37 min")
        guard case .number(let g)? = parsed["filamentGrams"] else { Issue.record("no grams"); return }
        #expect(abs(g - 57.18) < 0.05, "the shared rule rounds to 0.1 g")
        #expect(parsed["filamentType"] == .string("PLA"))
    }

    @Test("a G-code: the slicer's own summary")
    func gcode() async throws {
        let dir = FileManager.default.temporaryDirectory.appending(path: "sf-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appending(path: "part.gcode")
        let body = String(repeating: "G1 X1 Y1\n", count: 20_000)
        try Data(("; generated by PrusaSlicer 2.8\n" + body
                  + "; filament used [g] = 42.5\n; estimated printing time (normal mode) = 2h 5m 0s\n; filament_type = PETG\n").utf8)
            .write(to: url)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["filamentGrams"] == .number(42.5))
        #expect(parsed["printTimeMins"] == .number(125))
    }

    @Test("an unsliced model says nothing rather than guessing")
    func unsliced() async throws {
        let url = try zip(["3D/3dmodel.model": "<model/>"])
        #expect(await SlicerFigures.read(url, engine: try KhaytEngine()) == nil)
    }

    /// Opt-in, against a real file on this Mac: `KHAYT_REAL_3MF=/path swift test`.
    @Test("the shop's own file", .enabled(if: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"] != nil))
    func realFile() async throws {
        let url = URL(fileURLWithPath: ProcessInfo.processInfo.environment["KHAYT_REAL_3MF"]!)
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        print("REAL:", parsed)
    }

    @Test("two plates: the file is their SUM, and each plate is kept to be chosen")
    func twoPlates() async throws {
        let info = """
        <config>
        <plate><metadata key="index" value="1" /><metadata key="prediction" value="39284" />
          <filament id="1" type="PETG" used_g="143.44" /></plate>
        <plate><metadata key="index" value="2" /><metadata key="prediction" value="39154" />
          <filament id="1" type="PETG" used_g="100.00" /><filament id="2" type="PETG" used_g="42.95" /></plate>
        </config>
        """
        let url = try zip(["Metadata/slice_info.config": info, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        // The shared rule (`extractMeta`, #1602): the plates' seconds summed, then
        // rounded once — 39284 + 39154 s is 1307 min.
        #expect(parsed["printTimeMins"] == .number(1307), "BOTH plates' time, not the first plate's")
        #expect(parsed["filamentGrams"] == .number(286.4), "grams to 0.1 g, the shared rule's")
        #expect(parsed["platesRead"] == .number(Shop.platesReadVersion))
        guard case .array(let plates)? = parsed["plates"], plates.count == 2,
              case .object(let p2) = plates[1] else { Issue.record("no plates"); return }
        #expect(p2["index"] == .number(2) && p2["printTimeMins"] == .number(653) && p2["filamentGrams"] == .number(143.0))
    }

    @Test("a record is read again when it has no figures, or is a 3MF read before plates were")
    func due() {
        #expect(Shop.slicerFiguresDue(nil, ext: "3mf"))
        #expect(Shop.slicerFiguresDue(.object([:]), ext: "gcode"))
        #expect(Shop.slicerFiguresDue(.object(["printTimeMins": .number(5)]), ext: "3mf"))
        #expect(!Shop.slicerFiguresDue(.object(["printTimeMins": .number(5)]), ext: "gcode"))
        #expect(!Shop.slicerFiguresDue(.object(["printTimeMins": .number(5), "platesRead": .number(2)]), ext: "3mf"))
        // Read before plates carried their names and per-spool grams (Oct 2026):
        // once more, so the data already on disk gets them.
        #expect(Shop.slicerFiguresDue(.object(["printTimeMins": .number(5), "platesRead": .bool(true)]), ext: "3mf"))
    }

    @Test("a Bambu print file carrying plate 1's G-code is still read plate by plate")
    func printFileWithGcode() async throws {
        let info = """
        <config>
        <plate><metadata key="index" value="1" /><metadata key="prediction" value="3600" />
          <filament id="1" type="PLA" used_g="10" /></plate>
        <plate><metadata key="index" value="2" /><metadata key="prediction" value="7200" />
          <filament id="1" type="PLA" used_g="20" /></plate>
        </config>
        """
        let gcode = "; generated by BambuStudio\n; filament used [g] = 10\n; estimated printing time (normal mode) = 1h 0m 0s\n"
        let url = try zip(["Metadata/slice_info.config": info, "Metadata/plate_1.gcode": gcode, "3D/3dmodel.model": "<model/>"])
        let parsed = try #require(await SlicerFigures.read(url, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(180), "both plates, not plate 1's G-code")
        #expect(parsed["filamentGrams"] == .number(30))
    }

    @Test("an unsliced 3MF says nothing — and is marked read, so it is not opened every launch")
    func unslicedMarked() {
        #expect(!Shop.slicerFiguresDue(.object(["platesRead": .number(Shop.platesReadVersion)]), ext: "3mf"))
    }

    /// The fixture both apps' tests read — test/fixtures/two-plate-bambu.gcode.3mf,
    /// written by test/fixtures/make-two-plate-3mf.js. Every figure here is the
    /// one test/extract-meta-plates.test.js asserts for lib/model-intake.js, so
    /// the two readers are held to one answer for the same bytes.
    static let twoPlateFixture = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent().deletingLastPathComponent()
        .appending(path: "test/fixtures/two-plate-bambu.gcode.3mf")

    @Test("a real-shaped two-plate project: totals, plate names and each spool over both plates")
    func twoPlateFixture() async throws {
        let parsed = try #require(await SlicerFigures.read(Self.twoPlateFixture, engine: try KhaytEngine()))
        #expect(parsed["printTimeMins"] == .number(213), "90 + 123 min, not plate_1.gcode's 90")
        #expect(parsed["filamentGrams"] == .number(67.5), "34.75 + 32.75 g, not plate 1's")
        guard case .array(let plates)? = parsed["plates"], plates.count == 2,
              case .object(let p1) = plates[0], case .object(let p2) = plates[1] else {
            Issue.record("no plates"); return
        }
        #expect(p1["name"] == .string("Body") && p1["printTimeMins"] == .number(90) && p1["filamentGrams"] == .number(34.8))
        #expect(p2["name"] == .string("Lid") && p2["printTimeMins"] == .number(123) && p2["filamentGrams"] == .number(32.8))
        guard case .array(let spools)? = parsed["filaments"] else { Issue.record("no filaments"); return }
        let bySlot = spools.compactMap { v -> (String, Double)? in
            guard case .object(let f) = v, case .string(let id)? = f["id"], case .number(let g)? = f["grams"] else { return nil }
            return (id, g)
        }
        #expect(bySlot.map(\.0) == ["1", "2", "3"])
        #expect(bySlot.map(\.1) == [42.5, 4.25, 20.75], "slot 1 over both plates")

        // The colour list, through the same rule the import uses: each colour
        // carries the whole project's grams, adding up to the same 67.5 g.
        let engine = try KhaytEngine()
        let text = { (name: String) throws -> String in
            guard let e = try Zip.entries(of: Self.twoPlateFixture).first(where: { $0.name == name }) else { return "" }
            return String(decoding: try Zip.data(of: e, in: Self.twoPlateFixture), as: UTF8.self)
        }
        let found = try await engine.coloursFromConfigs(sliceInfo: try text("Metadata/slice_info.config"),
                                                       projectSettings: "", modelSettings: "", prusa: "")
        let grams = found.colors.compactMap { v -> Double? in
            if case .object(let c) = v, case .number(let g)? = c["grams"] { return g }; return nil
        }
        #expect(grams == [42.5, 4.25, 20.75])
    }

    @Test("a colour list written with plate 1's grams is repaired from the per-spool totals")
    func colourRepair() {
        let colours: JSONValue = .array([
            .object(["hex": .string("#000000"), "grams": .number(30.5), "label": .string("Filament 1")]),
            .object(["hex": .string("#FFFFFF"), "grams": .number(4.25)]),
            .object(["hex": .string("#123456"), "grams": .number(1)]),
        ])
        let spools: JSONValue = .array([
            .object(["id": .string("1"), "color": .string("#000000"), "grams": .number(42.5)]),
            .object(["id": .string("2"), "color": .string("#ffffff"), "grams": .number(4.25)]),
        ])
        guard case .array(let out)? = Shop.coloursWithProjectGrams(colours, filaments: spools),
              case .object(let black) = out[0], case .object(let other) = out[2] else {
            Issue.record("nothing repaired"); return
        }
        #expect(black["grams"] == .number(42.5))
        #expect(black["label"] == .string("Filament 1"), "everything else on the colour is kept")
        #expect(other["grams"] == .number(1), "a colour the slicer did not list keeps its grams")
        // Already right: nothing to write.
        #expect(Shop.coloursWithProjectGrams(.array([.object(["hex": .string("#000000"), "grams": .number(42.5)])]),
                                            filaments: spools) == nil)
    }
}
