import Foundation
import Testing
import KhaytCore
@testable import KhaytApp

/// Running the shop's slicer to find out what a model really takes.
///
/// A slicer is not on a test machine, so what is proved here is everything
/// around the spawn: the argv the slicer would be launched with, which comes
/// from the shared rule; finding the G-code afterwards; and reading the two
/// windows where the totals are without holding a sliced plate in memory.
@MainActor
struct SlicerRunTests {

    static func slicer(_ path: String, args: String = "") throws -> KhaytEngine.Slicer {
        try JSONDecoder().decode(KhaytEngine.Slicer.self, from: Data(
            #"{"id":"S1","name":"Test","path":"\#(path)","args":"\#(args)"}"#.utf8))
    }

    // MARK: - The argv, from the shared rule

    @Test("the argv is the shared rule's, and a path with a space stays one argument")
    func argvComesFromTheRule() async throws {
        let engine = try KhaytEngine()
        let argv = try await engine.sliceArgv(template: "-o {output} {model}",
                                              model: "/Users/x/My Models/dragon.stl",
                                              output: "/tmp/out dir/out.gcode", outdir: "/tmp/out dir")
        #expect(argv == ["-o", "/tmp/out dir/out.gcode", "/Users/x/My Models/dragon.stl"])

        // An empty template is the documented default rather than no arguments.
        let fallback = try await engine.sliceArgv(template: "", model: "m.stl",
                                                  output: "o.gcode", outdir: "d")
        #expect(fallback == ["--export-gcode", "-o", "o.gcode", "m.stl"])

        // A model path that looks like arguments cannot become any: it is
        // filled into a token that was already final.
        let nasty = try await engine.sliceArgv(template: "{model}",
                                               model: "a.stl --load /etc/evil.ini",
                                               output: "", outdir: "")
        #expect(nasty == ["a.stl --load /etc/evil.ini"])
    }

    // MARK: - Refusing before spawning

    @Test("it refuses a slicer the allowlist has not cleared, without running anything")
    func refusesDisallowed() throws {
        let s = try Self.slicer("/bin/sh")
        #expect(throws: SlicerRun.Failure.notAllowed("Test")) {
            try SlicerRun.slice(URL(fileURLWithPath: "/tmp/x.stl"), with: s, argv: [], allowed: false)
        }
    }

    @Test("a slicer that is not there, and a model that is not there, are told apart")
    func missingThings() throws {
        let gone = try Self.slicer("/nowhere/at/all")
        #expect(throws: SlicerRun.Failure.noSlicer) {
            try SlicerRun.slice(URL(fileURLWithPath: "/tmp/x.stl"), with: gone, argv: [], allowed: true)
        }
        // A real executable, but no model to give it.
        let real = try Self.slicer("/bin/echo")
        #expect(throws: SlicerRun.Failure.missingModel) {
            try SlicerRun.slice(URL(fileURLWithPath: "/nowhere/model.stl"), with: real, argv: [], allowed: true)
        }
    }

    // MARK: - Finding what it wrote

    @Test("the G-code we asked for, else whatever the slicer named it")
    func findsTheOutput() throws {
        let dir = try SlicerRun.scratch()
        defer { try? FileManager.default.removeItem(at: dir) }
        let asked = dir.appending(path: "out.gcode")
        #expect(SlicerRun.gcode(in: dir, expected: asked) == nil, "an empty directory produced a file")

        // Slicers rename output more often than they admit.
        let theirs = dir.appending(path: "dragon_0.2mm_PLA.gcode")
        try Data("; hello".utf8).write(to: theirs)
        #expect(SlicerRun.gcode(in: dir, expected: asked) == theirs)

        // And when it did as it was told, that one wins.
        try Data("; asked".utf8).write(to: asked)
        #expect(SlicerRun.gcode(in: dir, expected: asked) == asked)

        // Anything that is not G-code is ignored.
        try Data("x".utf8).write(to: dir.appending(path: "notes.txt"))
        #expect(SlicerRun.gcode(in: dir, expected: asked) == asked)
    }

    @Test("the totals are read from both ends, never the whole plate")
    func readsBothEnds() async throws {
        let dir = try SlicerRun.scratch()
        defer { try? FileManager.default.removeItem(at: dir) }
        let file = dir.appending(path: "big.gcode")

        // A header, a great deal of movement, and a footer — the shape of a
        // real sliced plate, where the totals sit at the two ends.
        let header = "; generated by SnapmakerOrca 2.3.6\n; estimated printing time (normal mode) = 4h 32m 11s\n"
        let middle = String(repeating: "G1 X10 Y10 E0.5\n", count: 40_000)
        let footer = "; filament used [g] = 140.91\n"
        try Data((header + middle + footer).utf8).write(to: file)
        let size = try #require(try FileManager.default.attributesOfItem(atPath: file.path)[.size] as? Int)
        #expect(size > 2 * SlicerRun.window, "the fixture is not big enough to prove anything")

        let text = try SlicerRun.totalsText(of: file)
        #expect(text.count < size, "the whole plate was read into memory")
        // Both ends survived the window.
        #expect(text.contains("estimated printing time"))
        #expect(text.contains("filament used [g] = 140.91"))

        // And the shared parser gets what it needs out of exactly that text.
        let engine = try KhaytEngine()
        let intake = try #require(try await engine.gcodeIntake(text: text))
        guard case .object(let o) = intake else { Issue.record("not an object"); return }
        #expect(o["filamentGrams"] == .number(140.91))
        #expect(o["printTimeMins"] == .number(272))
        #expect(o["exact"] == .bool(true))
    }

    @Test("a small file is read whole without asking for a window past its end")
    func readsSmallFiles() throws {
        let dir = try SlicerRun.scratch()
        defer { try? FileManager.default.removeItem(at: dir) }
        let file = dir.appending(path: "small.gcode")
        try Data("; filament used [g] = 12.5\n".utf8).write(to: file)
        let text = try SlicerRun.totalsText(of: file)
        #expect(text.contains("12.5"))
    }
}
